name: Quick Leaks Token
# checking every developer input area to make sure there are no secrets 

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'token to leak in source type commit'
        required: false
      commit_comment:
        description: 'token to leak in source type commit_comment'
        required: false
      content:
        description: 'token to leak in source type content'
        required: false
      discussion_body:
        description: 'token to leak in source type discussion_body'
        required: false
      discussion_comment:
        description: 'token to leak in source type discussion_comment'
        required: false
      discussion_title:
        description: 'token to leak in source type discussion_title'
        required: false
      gist_content:
        description: 'token to leak in source type gist_content'
        required: false
      gist_comment:
        description: 'token to leak in source type gist_comment'
        required: false 

permissions: write-all
  
jobs:
  leak_commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.commit }}
    steps:
     - name: Create a new install token
       id: get_workflow_token
       uses: peter-murray/workflow-application-token-action@v1
       with:
         application_id: ${{ secrets.APPLICATION_ID }}
         application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
         organization: ${{ secrets.ORGANIZATION }}
     - uses: actions/checkout@v3
       with:
         repository: github/quick-leaks
         ref: refs/tags/v1.0.0
         token: ${{ steps.get_workflow_token.outputs.token }}
         #token: ${{ secrets.INSTALL_TOKEN }}
     - name: Leak in commit
       uses: ./
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         #GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
       with:
         #repo: dsp-testing/quick-leaks-public
         repo: sneha-natekar/NewRepoWednesday
         token: ${{ github.event.inputs.commit }}
         location: commit
